#ifndef LEG2_DEFINITIONS
#define LEG2_DEFINITIONS

/*------------------------------------------*/
/*------ Calibration Values for Leg 2 ------*/
/*------------------------------------------*/
#define LEG2_LEG_A_CALIB_VAL       263935840LL
#define LEG2_LEG_B_CALIB_VAL       261914899LL

#define LEG2_LEG_A_RAD_PER_CNT   9.8039216e-09
#define LEG2_LEG_B_RAD_PER_CNT  -9.8039216e-09

#define LEG2_TRAN_A_CALIB_VAL      142278000LL
#define LEG2_TRAN_B_CALIB_VAL      142215958LL

#define LEG2_TRAN_A_RAD_PER_CNT -9.8039216e-09
#define LEG2_TRAN_B_RAD_PER_CNT  9.8039216e-09

#define LEG2_MOTOR_A_DIRECTION             1.0
#define LEG2_MOTOR_B_DIRECTION             1.0




// Ignore the lines below, they are used for the include magic.
#ifdef INCLUDE_LEFT_LEG
#define LEFT_LEG_A_CALIB_VAL     LEG2_LEG_A_CALIB_VAL
#define LEFT_LEG_B_CALIB_VAL     LEG2_LEG_B_CALIB_VAL

#define LEFT_LEG_A_RAD_PER_CNT   LEG2_LEG_A_RAD_PER_CNT
#define LEFT_LEG_B_RAD_PER_CNT   LEG2_LEG_B_RAD_PER_CNT

#define LEFT_TRAN_A_CALIB_VAL    LEG2_TRAN_A_CALIB_VAL
#define LEFT_TRAN_B_CALIB_VAL    LEG2_TRAN_B_CALIB_VAL 

#define LEFT_TRAN_A_RAD_PER_CNT  LEG2_TRAN_A_RAD_PER_CNT
#define LEFT_TRAN_B_RAD_PER_CNT  LEG2_TRAN_B_RAD_PER_CNT

#define LEFT_MOTOR_A_DIRECTION   LEG2_MOTOR_A_DIRECTION
#define LEFT_MOTOR_B_DIRECTION   LEG2_MOTOR_B_DIRECTION
#endif

#ifdef INCLUDE_RIGHT_LEG
#define RIGHT_LEG_A_CALIB_VAL    LEG2_LEG_A_CALIB_VAL
#define RIGHT_LEG_B_CALIB_VAL    LEG2_LEG_B_CALIB_VAL

#define RIGHT_LEG_A_RAD_PER_CNT  LEG2_LEG_A_RAD_PER_CNT
#define RIGHT_LEG_B_RAD_PER_CNT  LEG2_LEG_B_RAD_PER_CNT

#define RIGHT_TRAN_A_CALIB_VAL   LEG2_TRAN_A_CALIB_VAL
#define RIGHT_TRAN_B_CALIB_VAL   LEG2_TRAN_B_CALIB_VAL 

#define RIGHT_TRAN_A_RAD_PER_CNT LEG2_TRAN_A_RAD_PER_CNT
#define RIGHT_TRAN_B_RAD_PER_CNT LEG2_TRAN_B_RAD_PER_CNT

#define RIGHT_MOTOR_A_DIRECTION  LEG2_MOTOR_A_DIRECTION
#define RIGHT_MOTOR_B_DIRECTION  LEG2_MOTOR_B_DIRECTION
#endif

#endif //LEG2_DEFINITIONS
