uint8 status
float32 time

float32 body_angle
float32 body_angle_vel
float32 motor_angleA
float32 motor_angleA_inc
float32 motor_angleB
float32 motor_angleB_inc
float32 leg_angleA
float32 leg_angleB

float32 motor_velocityA
float32 motor_velocityB
float32 leg_velocityA
float32 leg_velocityB

float32 hip_angle
float32 hip_angle_vel

float32 xPosition
float32 yPosition
float32 zPosition

float32 xVelocity
float32 yVelocity
float32 zVelocity

uint8 motor_currentA
uint8 motor_currentB

uint8 toe_switch

uint8 command

float32[3] thermistorA
float32[3] thermistorB
float32 motorVoltageA
float32 motorVoltageB
float32 logicVoltageA
float32 logicVoltageB
uint8 medullaStatusA
uint8 medullaStatusB

uint8[256] control_state
float32 motor_torqueA
float32 motor_torqueB
