float64 walking_state
float64 atrias_spring
float64 slip_leg
float64 swing_leg_retraction
float64 force_threshold_td
float64 force_threshold_to
float64 position_threshold_td
float64 stance_leg_target
float64 flight_leg_target
float64 leg_pos_kp
float64 leg_for_kp
float64 leg_pos_kd
float64 leg_for_kd
float64 hip_pos_kp
float64 hip_pos_kd

uint8 main_controller
uint8 flight_to
uint8 flight_td

float64 td_force
float64 to_force
float64 td_position

bool debug
