#!/bin/sh

# Devin Koepl

if test \! -c /dev/rtai_shm; then
	mknod -m 666 /dev/rtai_shm c 10 254
fi
for n in `seq 0 9`; do
	f=/dev/rtf$n
	if test \! -c $f; then
		mknod -m 666 $f c 150 $n
	fi
done

# Commented out by yoos 10/03/11
# prefix=`rtai-config --prefix`
# 
# if test "$prefix" = ""; then
# echo "ERROR: please set your PATH variable to <rtai-install>/bin"
# exit
# fi

modprobe rtai_hal
modprobe rtai_ksched
modprobe rtai_sem
modprobe rtai_mbx
modprobe rtai_msg
modprobe rtai_fifos
modprobe rtai_tbx
modprobe rtai_bits
modprobe rtai_mq
modprobe rtai_shm
