uint8 command
uint8 controller_requested
uint8[256] control_data
---
uint8 status
float32 time
float32 body_angle
float32 motor_angleA
float32 motor_angleB
float32 leg_angleA
float32 leg_angleB
float32 motor_torqueA
float32 motor_torqueB
float32 motor_torque_hip
float32 motor_velocityA
float32 motor_velocityB
float32 motor_velocity_hip
float32 xPosition
float32 yPosition
float32 zPosition
float32 xVelocity
float32 yVelocity
float32 zVelocity
float32 horizontal_velocity
uint8[256] control_state
float32[3] thermistorA
float32[3] thermistorB
float32 motorVoltageA
float32 motorVoltageB
float32 logicVoltageA
float32 logicVoltageB
uint8 medullaStatusA
uint8 medullaStatusB

