clc
clear
close all
format compact


%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 09-Feb-2012 17:49:16

fileToRead1 = 'atrias_120209_173242.log';

DELIMITER = ',';
HEADERLINES = 1;

% Import the file
newData1 = importdata(fileToRead1, DELIMITER, HEADERLINES);

% Create new variables in the base workspace from those fields.
vars = fieldnames(newData1);
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

header_names = ['Time (ms), Body Angle, Motor A Angle, Motor A Angle (inc), Motor B Angle, Motor B Angle (inc), Leg A Angle, Leg B Angle, Body Angular Velocity, Motor A Velocity, Motor B Velocity, Leg A Velocity, Leg B Velocity, Hip Angle, Hip Angular Velocity, X Position, Y Position, Z Position, X Velocity, Y Velocity, Z Velocity, Horizontal Velocity, Motor A Current, Motor B Current, Toe Switch, Command, Thermistor A0, Thermistor A1, Thermistor A2, Thermistor B0, Thermistor B1, Thermistor B2, Motor A Voltage, Motor B Voltage, Logic A Voltage, Logic B Voltage, Medulla A Status, Medulla B Status, Motor A Torque, Motor B Torque';];

Ti = 1;
MAi = 3;
MBi = 5;
LAi = 7;
LBi = 8;

IAi = 3;
IBi = 5;

time = (data(:,Ti)-data(1,Ti))/1000;

defA = data(:,LAi)-data(:,MAi);
defB = data(:,LBi)-data(:,MBi);

% plot(time, defA,'r-', time, -defB,'b-')


peak_threshold = 0.1;
stance_threshold = 15e-3;

indices = find(abs((defA < peak_threshold).*10 + diff([10; defA])) < 0.75e-4)

peak_index = indices(1);
stance_indices = find(defA > stance_threshold);
stance_index = stance_indices(1);

time(peak_index)

time(stance_index)
peak_index
stance_index
desired_profileA = [defA(stance_index:peak_index); defA(peak_index:-1:stance_index)];
desired_profileB = [defB(stance_index:peak_index); defB(peak_index:-1:stance_index)];

%defA(stance_index:peak_index); 

plot([1:numel(desired_profileA)]*0.001, desired_profileA, 'b-', [1:numel(desired_profileB)]*0.001, -desired_profileB, 'r-', [1:numel(desired_profileB)]*0.001, mean([desired_profileA'; -desired_profileB']),'g-')

% figure
% plot(time, data(:,IAi)*180/pi, 'r-', time, data(:,IBi)*180/pi, 'b-')
