# Devin Koepl	

obj-m := rtai_controller.o 

rtai_controller-objs := rtai_controller_wrapper.o

EXTRA_CFLAGS := \
	-I /usr/realtime/include \
	-I `rospack find atrias`/include \
	-I /opt/etherlab/include	\
	$(shell rtai-config --module-cflags) \
	-I /usr/include \
	-ffast-math \
	-mhard-float \

KBUILD_EXTRA_SYMBOLS := \
	/usr/src/ethercat-default/Module.symvers \
	/usr/realtime/modules/Modules.symvers \
	/usr/src/linux-`uname -r`/Module.symvers

#------------------------------------------------------------------------------
