float64 des_motor_torque_left_A
float64 des_motor_torque_left_B
float64 des_motor_torque_left_hip
float64 des_motor_torque_right_A
float64 des_motor_torque_right_B
float64 des_motor_torque_right_hip

bool dutyCycleTest

uint8   dc_mode
float64 dc_freq
float64 dc_dc
float64 dc_spring_stiffness
float64 dc_hop_height
bool    dc_oscillate
float64 dc_oscillate_freq

float64 dc_ip
float64 dc_ic
float64 dc_tp
float64 dc_tc

bool limitCurrent

