float64 flight_leg_P_gain
float64 flight_leg_D_gain
float64 flight_hip_P_gain
float64 flight_hip_D_gain

float64 stance_leg_P_gain
float64 stance_leg_D_gain
float64 stance_hip_P_gain
float64 stance_hip_D_gain

bool constant_force
float64 fx
float64 fz

bool slip_force
float64 slip_height
float64 slip_mass
float64 slip_spring
float64 slip_leg

bool constant_hip
float64 hip_angle

bool advanced_hip
float64 left_hip_target
float64 right_hip_target

float64 robot_spring
float64 robot_motor

bool debug1
bool debug2
bool debug3
bool debug4
