# Devin Koepl

obj-m := rtai_medulla_safety_tester.o 

rtai_medulla_safety_tester-objs := medulla_safety_tester_kern.o 

EXTRA_CFLAGS := \
	-I /usr/realtime/include \
	-I /opt/etherlab/include	\
	-I `rospack find atrias`/include		\
	-I `rospack find atrias_controllers`/include		\
	-I `rospack find drl_library`/include		\
	$(shell rtai-config --module-cflags) \
	-I /usr/include \
	-ffast-math \
	-D COMPILE_FOR_RTAI

#KBUILD_EXTRA_SYMBOLS := \
#	/usr/src/ethercat-default/Module.symvers \
#	/usr/realtime/modules/Modules.symvers \
#	/usr/src/linux-`uname -r`/Module.symvers

#------------------------------------------------------------------------------
